simplify all prs fetch

diff --git a/gh-copr b/gh-copr
--- a/gh-copr
+++ b/gh-copr
@@ -2,13 +2,13 @@
 set -e
 
 help() {
-  cat <<EOF
-Usage: gh copr
-Display an interactive list of open PRs. The selected PR is checked out.
-Options:
-    -r filter prs that need your review 
-    --help show this message
-Dependencies: fzf
+	cat <<EOF
+		Usage: gh copr
+		Display an interactive list of open PRs. The selected PR is checked out.
+		Options:
+			-r filter prs that need your review 
+			--help show this message
+		Dependencies: fzf
 EOF
 }
 
@@ -19,38 +19,11 @@ fi
 
 # Make sure fzf is available
 if ! type -p fzf >/dev/null; then
-  echo "fzf not found on the system" >&2
-  exit 1
+	echo "fzf not found on the system, try:" 
+	echo "brew install fzf"
+	>&2
+	exit 1
 fi
-
-list_prs() {
-  # shellcheck disable=SC2016
-  gh api graphql --cache=5m -F owner='{owner}' -F repo='{repo}' -f query='
-    query ($owner: String!, $repo: String!) {
-      repository(owner: $owner, name: $repo) {
-        pullRequests(first: 100, states: [OPEN]) {
-          nodes {
-            number
-            title
-            author {
-              login
-            }
-            state
-            headRefName
-          }
-        }
-      }
-    }
-  ' --template '
-    {{- range .data.repository.pullRequests.nodes -}}
-      {{- .number | printf "#%.0f\t" | color "green" -}}
-      {{- .title | printf "%s\t" -}}
-      {{- .headRefName | printf "%s\t" | color "cyan" -}}
-      {{- .author.login | printf " by %s\t" -}}
-      {{- .state | printf "%s\n" -}}
-    {{- end -}}
-  ' | column -t -s$'\t'
-}
 
 pull_requests_that_need_my_review() {
 	template='{{range(pluck "node" .data.search.edges) -}}
@@ -102,6 +75,6 @@ while test $# != 0; do
 	shift
 done
 
-selected=$(fzf --ansi <<<"$(list_prs)")
+selected=$(fzf --ansi <<<"$(GH_FORCE_TTY=100% gh pr list | sed '1d;2d;3d;')")
 [ -n "$selected" ] || exit 1
 gh pr checkout "${selected%% *}"
